# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='accompanying_person',
        ),
        migrations.AlterField(
            model_name='guest',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
