# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='confirmed_adults',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='confirmed_children',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='confirmed_toddlers',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='food_type',
            field=models.CharField(blank=True, choices=[('Standardowe', 'Standardowe'), ('Wegetarianskie', 'Wegetarianskie'), ('Weganskie', 'Weganskie')], default='Standardowe', max_length=15),
        ),
    ]
