# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_auto_20180428_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='food_type',
            field=models.CharField(blank=True, choices=[('Standardowe', 'Standardowe'), ('Wegetarianskie', 'Wegetarianskie'), ('Weganskie', 'Weganskie')], default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='night_stay',
            field=models.CharField(blank=True, choices=[('Nie chc\u0119 pokoju', 'Nie chc\u0119 pokoju'), ('2-osobowy standard', '2-osobowy standard'), ('1-osobowy standard', '1-osobowy standard'), ('2-osobowy deluxe', '2-osobowy deluxe'), ('1-osobowy deluxe', '1-osobowy deluxe'), ('Apartament', 'Apartament')], default='', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='transport',
            field=models.CharField(blank=True, choices=[('Nie potrzeba', 'Nie potrzeba'), ('Spod ko\u015bcio\u0142a do hotelu', 'Spod ko\u015bcio\u0142a do hotelu'), ('Z placu przed kolegiat\u0105 Przemienienia Pa\u0144skiego w Radzyminie', 'Z placu przed kolegiat\u0105 Przemienienia Pa\u0144skiego w Radzyminie'), ('Z Dworca Wile\u0144skiego w Warszawie', 'Z Dworca Wile\u0144skiego w Warszawie')], default='', max_length=60, null=True),
        ),
    ]
