# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_guest_invitation_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information_Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
